# Generated by Django 5.0.6 on 2024-06-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(max_length=400, null=True)),
            ],
        ),
    ]
